# 日志等级
log_level: "info"

# HTTP 服务配置
http:
  # 是否启用
  enable: false
  # HTTP 服务端口
  port: 7005
  # 令牌
  token: "Karin-Puppeteer"

# karin 地址 可填写多个
karinUrl:
  - "ws://localhost:7000/puppeteer"

# 请求头id，用于标识请求头
headerId: "puppeteer"

# chromium 地址，填写edge/chromium的绝对路径，不推荐使用，自带的 chromium 更适合作为无头浏览器使用。
chromiumPath:

# puppeteer websocket 地址，连接单独存在的chromium。'ws://browserless:3000'
puppeteerWS:

# headless 模式
headless: true

# puppeteer启动args，注意args的--前缀
args:
  - --disable-gpu #"禁用GPU加速"
  - --disable-setuid-sandbox #"禁用setuid沙盒"
  - --no-sandbox #"禁用Chrome沙盒模式"
  - --no-zygote #"禁用zygote进程分割"
  - --disable-extensions #"禁用所有浏览器扩展"
  - --disable-dev-shm-usage #"避免使用/dev/shm，使用/tmp"

# 创建页面到达多少重启 chromium
createPageCount: 100

# 页面超时时间 默认15秒
timeout: 15000

# waitUntil参数设置 以下为可选值，对于纯静态页面，可以使用false
# false - 不等待任何事件，直接跳过等待，生成截图
# load - 页面的load事件触发时，代表页面所有资源都加载完毕才进行截图
# domcontentloaded - DOM树已经构建完毕，此时页面还在加载，慎用此选项
# networkidle0 - 网络空闲时触发，即网络连接数为0时触发 推荐使用此选项
# networkidle2 - 网络空闲时触发，即500毫秒内没有网络连接时触发 时间较久(500ms) 推荐使用networkidle0
waitUntil: networkidle0
